"""Domain constants shared across recommendation engines and UI."""

from __future__ import annotations

VALID_IPSILATERAL_SIDES = {"right", "left"}

SCORE_EXACT_MATCH = 95
SCORE_BASE_PARTIAL = 60
SCORE_BASE_HEURISTIC = 50
SCORE_MIN_RECOMMENDATION = 15
SCORE_MIN_HEURISTIC = 10
PENALTY_PER_WARNING = 5
HEURISTIC_PENALTY_PER_WARNING = 4

IDEAL_OVERSIZE_MIN = 10.0
IDEAL_OVERSIZE_MAX = 20.0
BORDERLINE_OVERSIZE_MIN = 8.0
BORDERLINE_OVERSIZE_MAX = 25.0
ILIAC_OVERSIZE_MAX = 25.0
TARGET_NECK_OVERSIZE = 15.0
TARGET_ILIAC_OVERSIZE = 12.0

MEDTRONIC_REQUIRED_OVERLAP_MM = 30.0
GORE_REQUIRED_OVERLAP_SMALL_MM = 16.0
GORE_REQUIRED_OVERLAP_LARGE_MM = 22.0

HOSTILE_NECK_LENGTH_MM = 10.0
SHORT_NECK_LENGTH_MM = 15.0
HOSTILE_NECK_DIAMETER_MM = 32.0
MIN_STANDARD_NECK_DIAMETER_MM = 16.0
MAX_STANDARD_NECK_DIAMETER_MM = 32.0
HOSTILE_NECK_ANGLE_DEG = 60.0
MIN_ILIAC_ACCESS_MM = 8.0
